# az-login.yml

name: Display Account Info

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 login:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: Azure/Login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Display Azure Account Info
        run: az account show -o yaml
        
